; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

upload_protocol = espota
upload_port = 10.38.99.104
upload_flags =
    --port=3232

board_build.partitions = partitions/custom.csv

build_flags =
    -Os

lib_deps =
    adafruit/DHT sensor library
    milesburton/DallasTemperature
    tzapu/WiFiManager
    bblanchon/ArduinoJson
    adafruit/Adafruit ADS1X15
    marcoschwartz/LiquidCrystal_I2C
    blynkkk/Blynk
    tzapu/WiFiManager
    bblanchon/ArduinoJson
    knolleary/PubSubClient